---
title: "Forecast Bias"
author: "Pauline"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

This looks at the forecast bias across different lead times. 
Also looks at the performance based on a 1-in-5 year RP.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(arrow)
library(gghdx)
options(scipen = 9999)
gghdx()
adm3_forecast <- read_parquet("../../TriggerApp2024/data/df_eth_mars_zonal_adm3.parquet")
  
adm3_actual <- read_parquet("../data/eth_adm3.parquet") %>%
  mutate(median = median*1000,
         date = as.Date(time),
         month = month(date),
         year = year(date),
         monthly_total = case_when(
           month %in% c(1, 3, 5, 7, 8, 10, 12) ~ median * 31,
           month %in% c(4, 6, 9, 11) ~ median * 30,
           month %in% c(2) ~ median * 29,
           (month %in% c(2) & year %% 4) ~ median * 29,
           .default = median))
```

The average rainfall by lead time.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
adm3_forecast %>%
  group_by(lt) %>%
  summarise(value_by_lt = mean(value, na.rm = T)) %>%
  ggplot() + 
    geom_line(aes(x = lt, y = value_by_lt)) + 
    labs(title = "Monthly Rainfall by Lead time", 
         x = "Lead time", 
         y = "Monthly Rainfall")
```



### Looking at a 1-in-5 RP by woreda

```{r, echo=FALSE, message=FALSE, warning=FALSE}
# getting the years by woreda with actual less than 20%
test_df <- adm3_actual %>%
  filter(admin3Pcode == "ET010101")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
hist(adm3_actual$monthly_total, freq = FALSE, 
     xlab = "Monthly Rainfall")
#lines(density(adm3_actual$monthly_total))
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}

```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
actual_df <- adm3_actual %>%
  group_by(admin3Pcode, month) %>%
  mutate(threshold = quantile(monthly_total, 0.2, na.rm = T), 
         below_thresh = monthly_total <= threshold)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
forecast_df <- adm3_forecast %>%
  group_by(adm3_pcode, valid_month, lt) %>%
  mutate(for_threshold = quantile(value, 0.2, na.rm = T), 
         for_below_thresh = value <= for_threshold)
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
combined_df <- actual_df %>%
  merge(forecast_df, by.x = c("admin3Pcode", "date"), by.y = c("adm3_pcode", "valid_date")) %>%
  mutate(
    bias = value - monthly_total,
    percent_bias = (bias*100) / monthly_total)
```

Testing which years the forecast would have triggered for OND.



```{r, echo=FALSE, message=FALSE, warning=FALSE}
combined_df %>%
  filter(for_below_thresh)
```



```{r, echo=FALSE, message=FALSE, warning=FALSE}
combined_df %>%
  group_by(lt) %>%
  summarise(TP = sum(below_thresh == T & for_below_thresh == T, na.rm = T),
            TN = sum(below_thresh == F & for_below_thresh == F, na.rm = T),
            FP = sum(below_thresh == F & for_below_thresh == T, na.rm = T),
            FN = sum(below_thresh == T & for_below_thresh == F, na.rm = T),
            FAR = FP / (FP+TN),
            FNR = FN / (FN+TP),
            TPR = TP / (TP+FN),
            F1 = (2 * TP) / ((2 * TP) + FN + FP)) %>%
  pivot_longer(!lt, names_to = "metrics", values_to = "values") %>%
  filter(metrics %in% c("FAR", "TPR")) %>%
  ggplot() +
  geom_line(aes(x = lt, y = values, group = metrics, color = metrics), size = 1) + 
  labs(title = "ECMWF Forecast Performance Metrics by lead time",
       y = "Value",
       x = "Lead time",
       color = "")
  
```

```{r echo=FALSE, message=FALSE, warning=FALSE}

combined_df %>%
  mutate(events = case_when(
    below_thresh & for_below_thresh ~ "Both",
    !below_thresh & for_below_thresh ~ "Forecast",
    below_thresh & !for_below_thresh ~ "Actual",
    !below_thresh & !for_below_thresh ~ "None",
    .default = ""
  )) %>%
  group_by(year, month, lt) %>%
  summarise(TP = any(events == "Both"),
            TN = all(events == "None"),
            FP = any(events == "Forecast"),
            FN = any(events == "Actual")) %>%
  mutate(across(c(TN, FP, FN), ~ifelse(TP, F, .))) %>%
  group_by(month, lt) %>%
  summarise(TP = sum(TP, na.rm = T),
            TN = sum(TN, na.rm = T),
            FP = sum(FP, na.rm = T),
            FN = sum(FN, na.rm = T),
            FAR = FP / (FP+TN),
            FNR = FN / (FN+TP),
            TPR = TP / (TP+FN),
            F1 = (2 * TP) / ((2 * TP) + FN + FP)) %>%
  pivot_longer(!c(month, lt), names_to = "metrics", values_to = "values") %>%
  filter(metrics %in% c("FAR", "FNR", "TPR")) %>%
  ggplot() +
  geom_line(aes(x = lt, y = values, group = metrics, color = metrics), size = 0.8) + 
  labs(title = "ECMWF Forecast Performance Metrics for OND by lead time",
       x = "Lead time",
       y = "Value",
       color = "") + 
  facet_wrap(~factor(month.abb[month], levels = month.abb))
  
```

