---
title: "Review of Seasons for Ethiopia"
author: "Pauline"
date: "`r Sys.Date()`"
output: 
  html_document:
    toc: true
    toc_float: true
    toc_collapsed: false
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Rainy Season Review by Admin Level (ERA5)

This document looks at possible seasons per each admin level for Ethiopia.

```{r, echo=FALSE, message=FALSE, warning=FALSE}
library(TriggerApp2024)
library(tidyverse)
library(shiny)
library(sf)
library(gghdx)
gghdx()
#ldf <- load_df_forecast(dataset = "mars_eth")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
eth_files <- list.files('../data', pattern = "eth_adm")
fp_eth_files <- file.path(
  "../data",
  eth_files
)
adm_level_labels <- stringr::str_extract(eth_files,"adm\\d")

ldf <- purrr::map(
  rlang::set_names(fp_eth_files, adm_level_labels),
  \(fp_tmp){
    arrow::read_parquet(
     fp_tmp
    )
  }
)

```

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
eth_adm1_codab <- st_read(
  file.path(
    Sys.getenv("AA_DATA_DIR"),
    "public", "raw", "eth", "cod_ab", "Admin_2024.gdb.zip"), 
  layer = "eth_admbnda_adm1_csa_bofedb_2024")

eth_adm3_codab <- st_read(
  file.path(
    Sys.getenv("AA_DATA_DIR"),
    "public", "raw", "eth", "cod_ab", "Admin_2024.gdb.zip"), 
  layer = "eth_admbnda_adm3_csa_bofedb_2024")

eth_lhz <- st_read(
  file.path(
    Sys.getenv("AA_DATA_DIR"),
    "public", "raw", "eth", "lhz", "ET_LHZ_2018"), 
  layer = "ET_LHZ_2018")
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
sliderInput("season_thresh", "Threshold Quantile for Season:", 0.5, min = 0, max = 1)
season_def <- list("JFM" = c(1,2,3),
                   "FMA" = c(2,3,4),
                   "MAM" = c(3,4,5),
                   "AMJ" = c(4,5,6),
                   "MJJ" = c(5,6,7),
                   "JJA" = c(6,7,8),
                   "JAS" = c(7,8,9),
                   "ASO" = c(8,9,10),
                   "SON" = c(9,10,11),
                   "OND" = c(10,11,12),
                   "NDJ" = c(11,12,1),
                   "DJF" = c(12,1,2))
get_seasons <- function(months) {
  seasons <- sapply(months, function(month) {
    matching_seasons <- names(Filter(function(x) month %in% x, season_def))
    if (length(matching_seasons) == 0) {
      return("")
    } else {
      return(matching_seasons)
    }
  })
  return(c(unlist(seasons)))
}

```

## At Country Level

### Seasonally

```{r, echo=FALSE, message=FALSE, warning=FALSE}
adm0_season_totals <- reactive({
  ldf$adm0 %>%
    rename_with(tolower, everything()) %>%
    mutate(valid_month = month(time),
           month_name = factor(month.abb[valid_month], levels = month.abb)) %>%
    slice(rep(row_number(), each = 3)) %>%
    mutate(season_name = get_seasons(month(ldf$adm0$time))) %>%
    group_by(admin0pcode, admin0name_en, season_name) %>%
    summarise(total_value = sum(median*1000, na.rm = TRUE)) %>%
    group_by(admin0pcode, admin0name_en) %>%
    mutate(season_thresh = quantile(total_value, probs = input$season_thresh), 
           in_season = ifelse(total_value >= season_thresh, "In-Seas", ""),
           season_name = factor(season_name, levels = names(season_def))) %>%
    arrange(season_name)
})

renderPlot({
  ggplot(adm0_season_totals()) + 
    geom_bar(aes(x=season_name, y=total_value), stat = "identity")+
    labs(title = "Seasonal Rainfall over Ethiopia", x = "Months", y = "Rainfall(mm)")+
    facet_wrap(~admin0name_en)
})
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
DT::renderDT({
  DT::datatable(
    adm0_season_totals() %>%
      group_by(admin0pcode, admin0name_en, season_name) %>%
      summarise(adm0_inseason = sum(in_season == "In-Seas") / n()) %>%
      dplyr::select(season_name, adm0_inseason) %>% 
      filter(adm0_inseason >= 0.5) %>%
      group_by(admin0pcode, admin0name_en) %>%
      summarise(seasons = paste(season_name, collapse = "-")),
  filter = "top", options = list(pageLength = -1, rownames = FALSE))
})
```


## At Regional Level

### Seasonally

```{r, echo=FALSE, message=FALSE, warning=FALSE}
adm1_season_totals <- reactive({
  ldf$adm1 %>%
    rename_with(tolower, everything()) %>%
    mutate(valid_month = month(time),
           month_name = factor(month.abb[valid_month], levels = month.abb)) %>%
    slice(rep(row_number(), each = 3)) %>%
    mutate(season_name = get_seasons(month(ldf$adm1$time))) %>%
    group_by(admin1pcode, admin1name_en, season_name) %>%
    summarise(total_value = sum(median*1000, na.rm = TRUE)) %>%
    group_by(admin1pcode, admin1name_en) %>%
    mutate(season_thresh = quantile(total_value, probs = input$season_thresh), 
           in_season = ifelse(total_value >= season_thresh, "In-Seas", ""),
           season_name = factor(season_name, levels = names(season_def))) %>%
    arrange(season_name)
})

renderPlot({
  ggplot(adm1_season_totals()) + 
    geom_bar(aes(x=season_name, y=total_value), stat = "identity")+
    labs(title = "Seasonal Rainfall over Ethiopia", x = "Months", y = "Rainfall(mm)")+
    facet_wrap(~admin1name_en)
})
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
DT::renderDT({
  DT::datatable(
    adm1_season_totals() %>%
      group_by(admin1pcode, admin1name_en, season_name) %>%
      summarise(adm1_inseason = sum(in_season == "In-Seas") / n()) %>%
      dplyr::select(season_name, adm1_inseason) %>% 
      filter(adm1_inseason >= 0.5) %>%
      group_by(admin1pcode, admin1name_en) %>%
      summarise(seasons = paste(season_name, collapse = "-")),
  filter = "top", options = list(pageLength = -1, rownames = FALSE))
})
```

## At Zonal Level

### Seasonally

```{r, echo=FALSE, message=FALSE, warning=FALSE}
adm2_season_totals <- reactive({
  ldf$adm2 %>%
    rename_with(tolower, everything()) %>%
    mutate(valid_month = month(time),
           month_name = factor(month.abb[valid_month], levels = month.abb)) %>%
    slice(rep(row_number(), each = 3)) %>%
    mutate(season_name = get_seasons(month(ldf$adm2$time))) %>%
    group_by(admin1pcode, admin1name_en, admin2pcode, admin2name_en, season_name) %>%
    summarise(total_value = sum(median*1000, na.rm = TRUE)) %>%
    group_by(admin1pcode, admin1name_en, admin2pcode, admin2name_en) %>%
    mutate(season_thresh = quantile(total_value, probs = input$season_thresh), 
           in_season = ifelse(total_value >= season_thresh, "In-Seas", ""),
           season_name = factor(season_name, levels = names(season_def))) %>%
    arrange(season_name)
})

DT::renderDT({
  DT::datatable(
    adm2_season_totals() %>%
      group_by(admin1pcode, admin1name_en, admin2pcode, admin2name_en, season_name) %>%
      summarise(adm2_inseason = sum(in_season == "In-Seas") / n()) %>%
      dplyr::select(season_name, adm2_inseason) %>% 
      filter(adm2_inseason == 1) %>%
      group_by(admin1pcode, admin1name_en, admin2pcode, admin2name_en) %>%
      summarise(seasons = paste(season_name, collapse = "-")),
  filter = "top", options = list(rownames = FALSE))
})
```


## At Woreda Level

### Seasonally

```{r, echo=FALSE, message=FALSE, warning=FALSE}
adm3_season_totals <- reactive({
  ldf$adm3 %>%
    rename_with(tolower, everything()) %>%
    mutate(valid_month = month(time),
           month_name = factor(month.abb[valid_month], levels = month.abb)) %>%
    slice(rep(row_number(), each = 3)) %>%
    mutate(season_name = get_seasons(month(ldf$adm3$time))) %>%
    group_by(admin1pcode, admin1name_en, admin2pcode, admin2name_en, admin3pcode, admin3name_en, season_name) %>%
    summarise(total_value = sum(median*1000, na.rm = TRUE)) %>%
    group_by(admin1pcode, admin1name_en, admin2pcode, admin2name_en, admin3pcode, admin3name_en) %>%
    mutate(season_thresh = quantile(total_value, probs = input$season_thresh), 
           in_season = ifelse(total_value >= season_thresh, "In-Seas", ""),
           season_name = factor(season_name, levels = names(season_def))) %>%
    arrange(season_name)
})

DT::renderDT({
  DT::datatable(
    adm3_season_totals() %>%
      group_by(admin1pcode, admin1name_en, admin2pcode, admin2name_en, admin3pcode, admin3name_en, season_name) %>%
      summarise(adm3_inseason = sum(in_season == "In-Seas") / n()) %>%
      dplyr::select(season_name, adm3_inseason) %>% 
      filter(adm3_inseason == 1) %>%
      group_by(admin1pcode, admin1name_en, admin2pcode, admin2name_en, admin3pcode, admin3name_en) %>%
      summarise(seasons = paste(season_name, collapse = "-")),
  filter = "top", options = list(rownames = FALSE))
})
```


### Plots of Seasons

#### MAM

```{r, echo=FALSE, message=FALSE, warning=FALSE}
renderPlot({
  adm3_season_totals() %>%
    filter(season_name == "MAM") %>%
    merge(eth_adm3_codab, by.y = "admin3Pcode", by.x = "admin3pcode") %>%
    ggplot() +
      geom_sf(aes(fill = in_season, geometry = Shape)) +
      geom_sf(data = eth_adm1_codab, fill = NA, linewidth = 0.8, color = "black") +
      labs(title = "Woredas in Season for MAM", fill = "In Season") +
      scale_fill_manual(values = c("In-Seas" = "#0F52BA")) + 
      guides(fill = "none")
})
```

#### JJA

```{r, echo=FALSE, message=FALSE, warning=FALSE}
renderPlot({
  adm3_season_totals() %>%
    filter(season_name == "JJA") %>%
    merge(eth_adm3_codab, by.y = "admin3Pcode", by.x = "admin3pcode") %>%
    ggplot() +
      geom_sf(aes(fill = in_season, geometry = Shape)) +
      geom_sf(data = eth_adm1_codab, fill = NA, linewidth = 0.8, color = "black") +
      labs(title = "Woredas in Season for JJA", fill = "In Season") +
      scale_fill_manual(values = c("In-Seas" = "#0F52BA")) + 
      guides(fill = "none")
})
```

#### OND

```{r, echo=FALSE, message=FALSE, warning=FALSE}
renderPlot({
  adm3_season_totals() %>%
    filter(season_name == "OND") %>%
    merge(eth_adm3_codab, by.y = "admin3Pcode", by.x = "admin3pcode") %>%
    ggplot() +
      geom_sf(aes(fill = in_season, geometry = Shape)) +
      geom_sf(data = eth_adm1_codab, fill = NA, linewidth = 0.8, color = "black") +
      labs(title = "Woredas in Season for OND", fill = "In Season") +
      scale_fill_manual(values = c("In-Seas" = "#0F52BA")) + 
      guides(fill = "none")
})
```

### Plots of Seasons with Livelihood Zones

*NOTE*: A woreda could have more than 1 livelihood zone.

```{r, echo=FALSE, message=FALSE, warning=FALSE, results='hide'}
livelihood <- st_transform(eth_lhz, st_crs(eth_adm3_codab))
joined_data <- st_join(eth_adm3_codab, livelihood, join = st_intersects) %>% 
  group_by(admin3Pcode) %>%
  distinct(LZTYPE, .keep_all = TRUE)
```

```{r, echo=FALSE, message=FALSE, warning=FALSE}
livelihood %>%
  ggplot() +
    geom_sf(aes(fill = LZTYPE, geometry = geometry)) +
    geom_sf(data = eth_adm1_codab, fill = NA, linewidth = 0.8, color = "black") +
    labs(title = paste0("Livelihood Zones"), fill = "Livelihoods")
```


```{r, echo=FALSE, message=FALSE, warning=FALSE}
selectInput("lztype", "Livelihood Zone:", sort(unique(eth_lhz$LZTYPE)[!is.na(unique(eth_lhz$LZTYPE))]))
```


#### MAM

```{r, echo=FALSE, message=FALSE, warning=FALSE}
out_data1 <- reactive({
  joined_data %>%
      filter(LZTYPE == input$lztype) %>%
      merge(adm3_season_totals() %>%
              filter(season_name == "MAM"), 
            by.y = "admin3pcode", by.x = "admin3Pcode", all.x = T)
})

renderPlot({
    out_data1() %>%
      mutate(ifelse(is.na(in_season), "", in_season)) %>%
      ggplot() +
        geom_sf(aes(fill = in_season, geometry = geometry)) +
        geom_sf(data = eth_adm1_codab, fill = NA, linewidth = 0.8, color = "black") +
        labs(title = paste0("Woredas in Season for MAM (", input$lztype, ")"), fill = "In Season") +
        scale_fill_manual(values = c("In-Seas" = "#0F52BA")) + 
        guides(fill = "none")
})
```

#### JJA

```{r, echo=FALSE, message=FALSE, warning=FALSE}
out_data2 <- reactive({
  joined_data %>%
      filter(LZTYPE == input$lztype) %>%
      merge(adm3_season_totals() %>%
              filter(season_name == "JJA"), 
            by.y = "admin3pcode", by.x = "admin3Pcode", all.x = T)
})

renderPlot({
     out_data2() %>%
      ggplot() +
        geom_sf(aes(fill = in_season, geometry = geometry)) +
        geom_sf(data = eth_adm1_codab, fill = NA, linewidth = 0.8, color = "black") +
        labs(title = paste0("Woredas in Season for JJA (", input$lztype, ")"), fill = "In Season") +
        scale_fill_manual(values = c("In-Seas" = "#0F52BA")) + 
        guides(fill = "none")
})
```

#### OND

```{r, echo=FALSE, message=FALSE, warning=FALSE}
out_data3 <- reactive({
  joined_data %>%
      filter(LZTYPE == input$lztype) %>%
      merge(adm3_season_totals() %>%
              filter(season_name == "OND"), 
            by.y = "admin3pcode", by.x = "admin3Pcode", all.x = T)
})

renderPlot({
     out_data3() %>%
      ggplot() +
        geom_sf(aes(fill = in_season, geometry = geometry)) +
        geom_sf(data = eth_adm1_codab, fill = NA, linewidth = 0.8, color = "black") +
        labs(title = paste0("Woredas in Season for OND (", input$lztype, ")"), fill = "In Season") +
        scale_fill_manual(values = c("In-Seas" = "#0F52BA")) + 
        guides(fill = "none")
})
```

